### ISSUE TITLE
Falsey values return original key

### ISSUE THREAD

**Issue by stellard** [jonschlinkert/rename-keys#10]
Hello Jon, 

I ran into an issue when trying to return 0 from the rename function since it evaluates to false.

Although falsey values are valid object keys they are incompatible with the current implementation. 

I am assuming here that your intention was probably to handle an undefined return value from the rename function by keeping the original key.

Maybe the tradeoff is to explicitly look for undefined when returning the original by default?

I've solved my problem by just starting my keys from 1 but I thought it was worth discussion anyways. 

Cheers, 

Scott

**Comment by jonschlinkert** [comment]
closed by https://github.com/jonschlinkert/rename-keys/pull/9

thanks!

**Comment by wootencl** [comment]
I'm uncertain whether or not #9 fixes this for empty strings. Will see if I can dig into it a little later today.
