### ISSUE TITLE
Recursive rename

### ISSUE THREAD

**Issue by emilbayes** [jonschlinkert/rename-keys#4]
Care if I submit a PR to add a recursive option?

**Comment by michaelkariv** [comment]
any news on that? I also need a recursive rename

**Comment by jonschlinkert** [comment]
Does this work? https://github.com/jonschlinkert/deep-rename-keys

**Comment by michaelkariv** [comment]
Thanks. I'll check it out. Meantime I forked and made similar changes. The important difference is that I pass a boolean to the function - that allows for both deep and shallow. 
https://github.com/michaelkariv/rename-keys
Thinking about it, my own need is always for the deep, so may be yours is better.

**Comment by jonschlinkert** [comment]
Whatever makes the most sense for your use case. I decided against adding a parameter to recurse, because - although the hits are very tiny - it does add complexity and makes it a little slower for most users. my thinking was that if you're going to rename nested keys, you probably won't need to do so "on the fly", you'll either do it or you won't, so publishing that as a separate lib seemed to make more sense. but that's all conjecture :)

**Comment by michaelkariv** [comment]
Nope, deep-rename-keys does not work for array-containing objects. Here is the test

it('should rename nested keys with array.', function () {
    var foo = rename({a: 'b', c: 'd', e: [{c: 'f'}, {c: 'h'}]}, function(key) {
        if (key === 'c') {
            return 'zzz';
        }
        return key;
    });
    assert.deepEqual(foo, {a: 'b', zzz: 'd', e: [{zzz: 'f'}, {zzz: 'h'}]});
});

**Comment by michaelkariv** [comment]
Your argument against adding a parameter has convinced me. But please check the array thing though. I am going to test my code with this use case too

**Comment by jonschlinkert** [comment]
I don't think it's really a bug, more of a feature. how about if we add a flag to recurse in arrays too?

**Comment by jonschlinkert** [comment]
actually I have a better idea (I think). one sec

**Comment by jonschlinkert** [comment]
I played around with a few solutions for this, but everything I've come up with so far adds quite a bit of overhead. I'll keep thinking on it though. I'm open to a pr

**Comment by michaelkariv** [comment]
Not yet with a PR. But just to showcase my need. Input is an XML with namespaces. xml2json provides a good object however the keys have XML namespaces in them. Hence the need to rename, and do so in a deep manner

**Comment by michaelkariv** [comment]
One more thing - using shallow rename function adds an overhead of verifying fn being a function for each depth dive. I think the solution is to write a new function, where fn verification is only done once.

**Comment by michaelkariv** [comment]
One more thing again - if I had to guess, I'd put my money on deep renaming being more of a need. In cases where the object is flat, the extra logic will not hurt. In cases where the object is really deep but only the top level needs renaming - yea it is a problem.

**Comment by jonschlinkert** [comment]
> In cases where the object is really deep but only the top level needs renaming - yea it is a problem.

I considered using a reduce function that exposes the current `typeof` to the callback, so the implementor can check the `typeof` to decided what to do. like if you're in an array versus an object. I don't think this would be too much of an impact.

**Comment by palanik** [comment]
Hey Guys, can I propose some enhancements.

1. Allowing the callback function to support additional arguments, which are parent keys - immediate parent first, followed by its parent ...
This gives the context of the key in the object to the callback function. Function implementor can selectively choose to rename keys of same name, but are at different level.
 
2. Arrays will have numeric keys. Array keys cannot be modified, hence the callback function is not called. But array keys will be passed to the callback function for child objects.

3. This will also be backward compatible with the current implementation as parent keys are additional arguments.

I can send you a PR to https://github.com/jonschlinkert/deep-rename-keys

I too prefer to keep deep rename function independent of shallow rename function. But would also prefer both functions  available in one library.

**Comment by jonschlinkert** [comment]
sounds great, I'd love to see the pr! thanks

**Comment by palanik** [comment]
Sent you the [PR](https://github.com/jonschlinkert/deep-rename-keys/pull/1).
Obviously, the code can be refined before it is released.

**Comment by michaelkariv** [comment]
Are you pulling this?

**Comment by doowb** [comment]
Closing this issue since the PR applies to `deep-rename-keys`.
