### ISSUE TITLE
Immutable execution

### ISSUE THREAD

**Issue by brycehanscomb** [jonschlinkert/rename-keys#6]
Can there be a way to immutably rename the keys? ie: returns a new object instead of mutating the source?

**Comment by jonschlinkert** [comment]
I've thought about this, we'd need to create new properties and delete the old ones, I'm not sure of any way around this. But at least we'd be mutating the original object. thoughts?

**Comment by brycehanscomb** [comment]
What about something like this that constructs a new object...
```js
return Object.keys(source).reduce(function(acc, key) {
		acc[__NEW_KEY_NAME__] = source[__OLD_KEY_NAME__];
		return acc;
	}, {});
```

**Comment by jonschlinkert** [comment]
that's technically what it's doing now. the accumulator is, in effect, doing a shallow clone. 

or, similar to what I mentioned above we could pass `source` as the accumulator, then we would need to delete the source property after creating a new one

**Comment by brycehanscomb** [comment]
I think shallow clone is appropriate behaviour, cheers.

**Comment by jonschlinkert** [comment]
I'm inclined to agree, I think it's the right behavior. going to close for now
